[package]
name = "megachess"
version = "0.1.0"
authors = ["Neidhart Orlich <neidhart.orlich@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.15.0"
log = { version = "0.4.8", features = ["serde"] }
ncollide3d = "0.21.0"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
