[package]
name = "megachess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
nakama-rs = "*"
nanoserde = "0.1.29"
futures = "0.3.15"
instant = "0.1.12"

[target.'cfg(target_os = "windows")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
