version: "3.9"
services:
  nginx:
    ports:
      - "443:443"
      - "80:80"
      - "3537:3537"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    image: nginx
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  matchbox:
    image: "jhelsing/matchbox-server:0.5"
    ports:
      - "3536:3536"
  coturn:
    image: "coturn/coturn"
    ports:
      - "3478:3478"
    volumes:
      - ./docker/turnserver.conf:/etc/coturn/turnserver.conf
