version: "3.9"
services:
  matchbox:
    image: "jhelsing/matchbox-server:0.6"
    ports:
      - "3536:3536"
  coturn:
    image: "coturn/coturn"
    network_mode: "host"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
  game-server:
    image: "neidhart/bugchess-server"
    volumes:
      - ./error_reports/:/error_reports
