version: "3.9"
services:
  matchbox:
    image: "jhelsing/matchbox-server:v0.14.0"
    ports:
      - "3536:3536"
    networks:
      - bugchess_network
  coturn:
    image: "coturn/coturn"
    ports:
      - "3478:3478"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    network_mode: "host"
  game-server:
    image: "neidhart/bugchess-server"
    volumes:
      - ./error_reports/:/error_reports
    networks:
      - bugchess_network

networks:
  bugchess_network:
    name: bugchess_network
    external: true
