version: '3'
services:
  ssl-proxy:
    container_name: ssl-proxy
    image: fsouza/docker-ssl-proxy
    depends_on:
      - nakama
    environment:
      - TARGET_PORT=7350
      - TARGET_HOST=nakama
      - TARGET_SCHEME=http
      - SSL_PORT=443
    volumes:
      - ./data:/etc/nginx/certs
    expose:
      - "443"
    ports:
      - "443:443"
  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"
  nakama:
    container_name: nakama
    image: heroiclabs/nakama:3.2.1
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama --config /nakama/data/config.yml --database.address postgres:localdb@postgres:5432/nakama
    restart: always
    links:
      - "postgres:db"
    depends_on:
      - postgres
    volumes:
      - ./data/:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data: