name: Game Wasm

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "game-server/**"
      - "docker/**"
      - "**.txt"
      - "**.md"


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    environment: heartlabs.tech
    steps:
    - name: Install prerequisites
      run: sudo apt-get update --fix-missing && sudo apt-get -y install libasound2-dev libgl1-mesa-dev xorg-dev binaryen wabt
    - name: Setup Rust environment
      uses: raftario/setup-rust-action@v1.0.0
      with:
        rust-target: wasm32-unknown-unknown  
    - name: Setup wasm-bindgen
      run: cargo install -f wasm-bindgen-cli
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --workspace
    - name: Build
      run: chmod a+x ./build.sh && ./build.sh
    - name: Compress
      run: >
        cd target/wasm32-unknown-unknown/release/
        && wasm-opt -Os -o megachess-opt.wasm megachess.wasm
##       enable for even smaller sizes:
##        && wasm-strip megachess-opt.wasm
##       && wasm-opt -Os --dce -o megachess-opt.wasm megachess-opt.wasm
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare Release
      run: zip -r megachess_wasm.zip html
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          megachess_wasm.zip
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
    - name: copy static files via ssh
      uses: appleboy/scp-action@master
      with:
        host: v2202204174441188151.happysrv.de
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_USER_PASSWORD }}
        source: "html/*"
        target: "/home/server/docker/html"
        strip_components: 1
    
    
