name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Rust environment
      uses: raftario/setup-rust-action@v1.0.0
      with:
        rust-target: wasm32-unknown-unknown         
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
    - name: Run tests
      run: cargo test --verbose
