name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install prerequisites
      run: sudo apt-get -y install libasound2-dev libgl1-mesa-dev xorg-dev
    - name: Setup Rust environment
      uses: raftario/setup-rust-action@v1.0.0
      with:
        rust-target: wasm32-unknown-unknown  
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --target wasm32-unknown-unknown --release
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: 'target/wasm32-unknown-unknown/release/megachess.wasm'
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
#    - name: Run tests
#      run: cargo test --verbose
